### ISSUE TITLE
Guide on how to run offline doesn't apply anymore

### ISSUE THREAD

**Issue by cburgdorf** [MyCryptoHQ/mycrypto.com#102]
I just wanted to make you folks aware that the [description on how to run MyCrypto locally](https://support.mycrypto.com/offline/running-mycrypto-locally.html) doesn't apply anymore.

There is no `index.html` that the user could run without installing dependencies and running the build before.

**Comment by tayvano** [comment]
Added for 3.14.0 and will remember to do for this latest build
