### ISSUE TITLE
Zip missing for v3.14.0 - Release

### ISSUE THREAD

**Issue by MysticRyuujin** [MyCryptoHQ/mycrypto.com#103]
I'm not totally concerned with the missing zip for v3.14.0 so long as the next release has a zip 😄 

Not sure why it wasn't included in the release?

**Comment by tayvano** [comment]
Whoops—added. Thanks for bringing it to our attention. 

The reason? Automation has spoiled us and I simply forgot this bit that hasn't been automated. ☹

**Comment by MysticRyuujin** [comment]
@tayvano It's broken again :(

**Comment by tayvano** [comment]
Fixed it. This will likely be one of the last releases. All development efforts have been moved to the new site @ https://github.com/mycryptohq/mycrypto and https://download.mycrypto.com/

**Comment by MysticRyuujin** [comment]
Thanks! So if we're running an offline node we should switch to the release over on https://github.com/mycryptohq/mycrypto ?

**Comment by tayvano** [comment]
Yup! The Electron apps are pretty nice and fancy but the standalone package is probably what you are more familiar with. Let us know what you think
