### ISSUE TITLE
mew.giveth.io node doesnt work on local version

### ISSUE THREAD

**Issue by GriffGreen** [MyCryptoHQ/mycrypto.com#113]
<img width="1300" alt="screen shot 2018-04-29 at 12 14 01 pm" src="https://user-images.githubusercontent.com/14945613/39405534-e34320a0-4ba6-11e8-9f6a-05e82c6467f7.png">

Error message from dev tools
2index.html#send-transaction:1 Failed to load https://mew.giveth.io/: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header has a value 'http://null' that is not equal to the supplied origin. Origin 'null' is therefore not allowed access.

**Comment by wbobeirne** [comment]
Seems to be working fine for me now, must have been an intermittent issue with their node. Let me know if you can reproduce it again.
