### ISSUE TITLE
Parity Phrase help link dead

### ISSUE THREAD

**Issue by HenryNguyen5** [MyCryptoHQ/mycrypto.com#135]
### Description
Clicking on the help link for Parity Phrase leads to a [dead link](https://support.mycrypto.com/private-keys-passwords/parity-phrases-are-no-longer-supported.html)

![2018-05-18-191100_615x343_scrot](https://user-images.githubusercontent.com/6404866/40261549-3979863a-5acf-11e8-8362-3058c2ee7632.png)

**Comment by tayvano** [comment]
It lives! Brought it back on the knowledge base side of things; same URL: https://support.mycrypto.com/private-keys-passwords/parity-phrases-are-no-longer-supported.html

**Comment by soc1c** [comment]
in case someone is looking for this in 2020:

TL;DR download `dist-v3.9.0-parityenabled.zip` from https://github.com/MyEtherWallet/etherwallet/releases/tag/v3.9.0

ref https://github.com/MyEtherWallet/knowledge-base-v3/blob/master/dist/private-keys-passwords/parity-phrases-are-no-longer-supported.html#L206
