### ISSUE TITLE
how to join to translate it into Chinese?

### ISSUE THREAD

**Issue by spyhole** [MyCryptoHQ/mycrypto.com#36]

**Comment by wbobeirne** [comment]
Thanks for showing interest in helping out! You can find our current translations over here: https://github.com/MyCryptoHQ/mycrypto.com/blob/master/app/scripts/translations/zhcn.js

If you'd like to make any changes, just click on the pencil at the top of the file, make your changes, and hit "Commit Changes" when you're done. We'll review the changes, and if it all looks good, will merge it in.

---


感谢您对帮助感兴趣！你可以在这里找到我们目前的翻译：https://github.com/MyCryptoHQ/mycrypto.com/blob/master/app/scripts/translations/zhcn.js

如果您想进行任何更改，只需单击文件顶部的铅笔，进行更改，然后在完成后点击“提交更改”。我们会审查所做的更改，如果一切看起来不错，都会将其添加到网站中。

翻譯自谷歌翻譯，抱歉的不准確。
