### ISSUE TITLE
Typo in "private key warning" text

### ISSUE THREAD

**Issue by esllou** [MyCryptoHQ/mycrypto.com#37]
Currently: Entering your private key on a website dangerous.

Correct to: Entering your private key on a website is dangerous.

![screenshot-2018-2-17 mycrypto com mycrypto com](https://user-images.githubusercontent.com/17408565/36339051-8972698e-13b4-11e8-83ef-c064b8276bd9.png)

**Comment by hahnmichaelf** [comment]
@esllou I'm surprised you were the first person to point this out as these warnings have been there for a few months. Thank you!

**Comment by tayvano** [comment]
🤦
Thank you @esllou
