### ISSUE TITLE
Add new ci setting for mycrypto.com

### ISSUE THREAD

**Issue by eastcoinuser** [MyCryptoHQ/mycrypto.com#46]
Is there any ci server or services for mycrypto.com gh-pages release?

**Comment by wbobeirne** [comment]
Hey @eastcoinuser,

Most of our development efforts are going towards an upcoming rewrite of the app. The new version uses Travis CI to run unit and integration tests, and we're using our own module [drawbridge](https://github.com/MyCryptoHQ/drawbridge) for hash-verified deploys. You can find that repo over here: https://github.com/MyCryptoHQ/MyCrypto

We probably won't be implementing any CI for the rest of this repo's lifetime, as there aren't any tests to run, and we probably only have a couple more deploys left until the new version is launched.
