### ISSUE TITLE
Please add NTK

### ISSUE THREAD

**Issue by dec1** [MyCryptoHQ/mycrypto.com#58]
It seems impossible to sign a transaction offline for a token (eg NTK) that is not already in the list of default tokens?
ie "add a custom token" and "send offline" cant be combined?

If so, can you please  add NTK as a default token asap, as I want to move it (offline).

Many thanks in Advance.

https://etherscan.io/token/0x69beab403438253f13b6e92db91f7fb849258263

**Comment by Azarielle** [comment]
#59

**Comment by dec1** [comment]
Thank you

**Comment by hahnmichaelf** [comment]
@Azarielle  @dec1 
You're going to want to follow our instructions here to get this added as a default token: https://support.mycrypto.com/tokens/token-creators-add-your-token-to-mycrypto.html

We pull from the ethereum-lists repository ( https://github.com/ethereum-lists/tokens/ ) to get our tokens now. Let me know if you need any help :)

**Comment by dec1** [comment]
I dont get it. It seems the pull request was merged into the master branch on Mar 26
https://github.com/MyCryptoHQ/mycrypto.com/pull/59/files
And the current release (apparently 12 days old)  is 3.15.0 according to 
https://github.com/MyCryptoHQ/mycrypto.com/releases.
And https://mycrypto.com/   reports the version to be 3.15.1

So why isnt NTK in the current release if it was merged into master before the release?
(And why does mycrypto.com release version differ from github?)
