### ISSUE TITLE
Contract function call arguments not returning same result as Remix and etherscan

### ISSUE THREAD

**Issue by PhABC** [MyCryptoHQ/mycrypto.com#62]
Having some issues with calling a function on a [deployed contract](https://rinkeby.etherscan.io/address/0x670fc78f3fb7649f0648243a292771934c3c1175) (rinkeby). 

When calling the function on remix or etherscan, it returns `true`, but when trying to call the same function with the same arguments on MyCrypto (MEW as well), then function returns `false`. The function requires the v,s,r arguments for the `ecrecover()` function in solidity. 

**MyCrypto**
![image](https://user-images.githubusercontent.com/9306422/37099961-bb148d5c-21ef-11e8-824e-722ad266cf98.png)

**Remix**
![image](https://user-images.githubusercontent.com/9306422/37100028-e6a2f904-21ef-11e8-8d5f-ec211998d671.png)

**Etherscan**
![image](https://user-images.githubusercontent.com/9306422/37100014-da63c51a-21ef-11e8-9a55-82c0c2892567.png)

The 4 input arguments I am using are ; 
_add : "0xd046b3c521c0f5513c8a47eb3c2011684ea80b27", 
v : "0x1b", 
r : "0x11e64b1e177fc75b859b4e55182e09b96b4518349c8a9ab438dac568ac78e7d3", 
s : "0x4a0843d860a38bfa5fecb393959b5ea8fd35803ab8935af9ec84d268e00e6b3f"

**Comment by tayvano** [comment]
Hey @PhABC—can you confirm this is also happening on beta.mycrypto.com? This codebase is being deprecated and were really trying to focus all efforts on the new codebase moving forward. If it doesnt work on beta, we'll be sure it get it fixed on both.

**Comment by PhABC** [comment]
Ah! Solved on the beta version apparently :). Same inputs return false on regular MyC and MEW. 

![image](https://user-images.githubusercontent.com/9306422/37112008-55585848-220f-11e8-8150-9c4be017e3fb.png)

Beta looks slick by the way! Congrats.
