### ISSUE TITLE
Bug when generating contract transaction offline

### ISSUE THREAD

**Issue by mikemyers1** [MyCryptoHQ/mycrypto.com#63]
When I try to generate a contract transaction offline using this guide: https://coss.io/coss-token-based-fee-split-allocation-tutorial, I get the following javascript error:

```
TypeError: data[0] is undefined
Stack trace:
[63]</customNode.prototype.getTransactionData/<@file:///home/ghost/crypto/mycrypto-v3.12.0/js/mycrypto-master.js:8076:9
[63]</customNode.prototype.rawPost/<@file:///home/ghost/crypto/mycrypto-v3.12.0/js/mycrypto-master.js:8133:9
processQueue@file:///home/ghost/crypto/mycrypto-v3.12.0/js/mycrypto-master.js:45350:39
scheduleProcessQueue/<@file:///home/ghost/crypto/mycrypto-v3.12.0/js/mycrypto-master.js:45399:9
$digest@file:///home/ghost/crypto/mycrypto-v3.12.0/js/mycrypto-master.js:46508:17
$apply@file:///home/ghost/crypto/mycrypto-v3.12.0/js/mycrypto-master.js:46797:15
done@file:///home/ghost/crypto/mycrypto-v3.12.0/js/mycrypto-master.js:40895:38
completeRequest@file:///home/ghost/crypto/mycrypto-v3.12.0/js/mycrypto-master.js:41131:9
requestError@file:///home/ghost/crypto/mycrypto-v3.12.0/js/mycrypto-master.js:41060:11
 Possibly unhandled rejection: {}
```

I used the code from mycrypto-v3.12.0.zip
The error happen when I click on "Generate transaction"

**Comment by tayvano** [comment]
Hey @mikemyers1—can you confirm this is also happening on beta.mycrypto.com? This codebase is being deprecated and were really trying to focus all efforts on the new codebase moving forward. If it doesnt work on beta, we'll be sure it get it fixed on both.

Thanks

**Comment by tayvano** [comment]
I would urge any further conversation on this issue to be moved to https://github.com/MyCryptoHQ/MyCrypto/issues/1495, or a new issue be opened in the new repo. This repo is only going to be utilized for the next ~2wks. :)
