### ISSUE TITLE
Enhancement: Add, "ARY" to list of ETH Tokens 

### ISSUE THREAD

**Issue by blockarray** [MyCryptoHQ/mycrypto.com#70]
We would like to ask that ARY, the Block Array ERC-20 Token be added to the [MyCrypto list of tokens please.](https://github.com/MyCryptoHQ/mycrypto.com/blob/master/app/scripts/tokens/ethTokens.json)

Website: www.blockarray.com

Etherscan Token Contract: https://etherscan.io/address/0xa5F8fC0921880Cb7342368BD128eb8050442B1a1

Json:

`{
"address":"0xa5F8fC0921880Cb7342368BD128eb8050442B1a1",
"symbol":"ARY",
"decimal":18,
"type":"default"
}
`

Please let us know if you require any other information or if we should submit a pull request! 

Keep up the good work and thank you!

twitter: @blockarraygroup

**Comment by hahnmichaelf** [comment]
@blockarray You're going to want to follow our instructions here to get this added as a default token: https://support.mycrypto.com/tokens/token-creators-add-your-token-to-mycrypto.html

We pull from the ethereum-lists repository ( https://github.com/ethereum-lists/tokens/ ) to get our tokens now. Let me know if you need any help :)
